document.addEventListener("DOMContentLoaded", function () {
  const form = document.getElementById("dataForm");
  const table = document.getElementById("dataTable");

  document.getElementById("usernameDisplay").innerText =
    localStorage.getItem("user");

  document.getElementById("searchInput").addEventListener("input", loadData);
  document.getElementById("filterType").addEventListener("change", loadData);

  function loadData() {
    const data = JSON.parse(localStorage.getItem("entries")) || [];
    const table = document.getElementById("dataTable");
    const searchValue = document
      .getElementById("searchInput")
      .value.toLowerCase();
    const filterType = document.getElementById("filterType").value;

    table.innerHTML = "";

    let total = 0;
    let ssdi = 0;
    let auto = 0;

    data.forEach((item, index) => {
      if (
        (item.name.toLowerCase().includes(searchValue) ||
          item.phone.toLowerCase().includes(searchValue)) &&
        (filterType === "" || item.type === filterType)
      ) {
        total++;

        if (item.type === "SSDI") ssdi++;
        if (item.type === "AUTO") auto++;

        table.innerHTML += `
                <tr>
                    <td data-label="Phone">${item.phone}</td>
                    <td data-label="Name">${item.name}</td>
                    <td data-label="Verifier Name">${item.verifier}</td>
                    <td data-label="Type">${item.type}</td>
                    <td data-label="Date">${item.date}</td>
                    <td data-label="Action">
                        <button class="action-btn" onclick="deleteEntry(${index})">Delete</button>
                    </td>
                </tr>`;
      }
    });

    document.getElementById("totalCount").innerText = total;
    document.getElementById("ssdiCount").innerText = ssdi;
    document.getElementById("autoCount").innerText = auto;
  }

  form.addEventListener("submit", function (e) {
    e.preventDefault();

    const entry = {
      phone: document.getElementById("phone").value,
      name: document.getElementById("name").value,
      verifier: document.getElementById("verifier").value,
      type: document.getElementById("type").value,
      date: document.getElementById("date").value,
    };

    const data = JSON.parse(localStorage.getItem("entries")) || [];
    data.push(entry);
    localStorage.setItem("entries", JSON.stringify(data));

    form.reset();
    loadData();
  });

  window.downloadProtectedPDF = function () {
    const { jsPDF } = window.jspdf;

    const data = JSON.parse(localStorage.getItem("entries")) || [];
    const selectedMonth = document.getElementById("monthPicker").value;

    if (!selectedMonth) {
      alert("Please select a month!");
      return;
    }

    const filteredData = data.filter((item) =>
      item.date.startsWith(selectedMonth),
    );

    if (filteredData.length === 0) {
      alert("No data found for selected month!");
      return;
    }

    const password = prompt("Enter password to protect this PDF:");
    if (!password) return;

    // 🔐 Create PDF with password protection
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
      encryption: {
        userPassword: password,
        ownerPassword: password,
        userPermissions: ["print"],
      },
    });

    // ✅ Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(102, 126, 234);
    doc.text("Monthly Data Report", 105, 15, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text(`Month: ${selectedMonth}`, 14, 25);

    // ✅ Table Headers
    let startY = 35;
    doc.setFillColor(102, 126, 234);
    doc.setTextColor(255, 255, 255);
    doc.rect(10, startY - 8, 190, 8, "F"); // header background
    doc.text("No.", 12, startY - 1);
    doc.text("Phone", 25, startY - 1);
    doc.text("Name", 60, startY - 1);
    doc.text("Verifier", 110, startY - 1);
    doc.text("Type", 150, startY - 1);
    doc.text("Date", 170, startY - 1);

    // ✅ Table Rows
    doc.setTextColor(0, 0, 0);
    filteredData.forEach((item, index) => {
      const rowY = startY + index * 8;

      // Alternate row background
      if (index % 2 === 0) {
        doc.setFillColor(240, 240, 240);
        doc.rect(10, rowY - 6, 190, 8, "F");
      }

      doc.text(`${index + 1}`, 12, rowY);
      doc.text(item.phone, 25, rowY);
      doc.text(item.name, 60, rowY);
      doc.text(item.verifier, 110, rowY);
      doc.text(item.type, 150, rowY);
      doc.text(item.date, 170, rowY);
    });

    // ✅ Footer
    doc.setFontSize(10);
    doc.setTextColor(100);
    const pageCount = doc.getNumberOfPages();
    doc.text(`Generated by CodeCompass ©2026`, 105, 290, { align: "center" });

    // ✅ Save PDF
    doc.save(`Monthly_Report_${selectedMonth}.pdf`);
  };

  window.deleteEntry = function (index) {
    const data = JSON.parse(localStorage.getItem("entries")) || [];
    data.splice(index, 1);
    localStorage.setItem("entries", JSON.stringify(data));
    loadData();
  };

  window.toggleForm = function () {
    const form = document.getElementById("formContainer");
    const icon = document.getElementById("toggleIcon");

    form.classList.toggle("active");

    icon.innerText = form.classList.contains("active") ? "−" : "+";
  };

  window.toggleTable = function () {
    const tableWrapper = document.getElementById("tableContainer");
    const icon = document.getElementById("toggleTableIcon");

    tableWrapper.classList.toggle("active");

    icon.innerText = tableWrapper.classList.contains("active") ? "−" : "+";
  };

  window.logout = function () {
    localStorage.removeItem("isLoggedIn");
    localStorage.removeItem("user");
    window.location.href = "index.html";
  };

  loadData();
});
